/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Custom OpenRoom colors
        void: {
          900: '#0A0A0F',
          800: '#12121A',
          700: '#1A1A26',
          600: '#252536',
          500: '#3A3A50',
          400: '#5A5A78',
          300: '#8A8AA8',
          200: '#B8B8D0',
          100: '#E8E8F0',
        },
        amber: {
          50: '#FEF9E8',
          100: '#FCEFC0',
          200: '#F9DF8D',
          300: '#F5CB4E',
          400: '#E8B820',
          500: '#C99A10',
          600: '#A17A0A',
          700: '#7A5C08',
        },
        'scholar-blue': '#4A90D9',
        'scout-green': '#5BBD76',
        'builder-orange': '#E8913A',
        'critic-red': '#D94A4A',
        'commander-purple': '#9B6DD1',
        'alchemist-teal': '#4AD9C9',
        'xp-gold': '#FFD700',
        'quest-green': '#4ADE80',
        'health-red': '#EF4444',
        'mana-blue': '#60A5FA',
        'rarity-common': '#9CA3AF',
        'rarity-uncommon': '#4ADE80',
        'rarity-rare': '#60A5FA',
        'rarity-epic': '#A78BFA',
        'rarity-legendary': '#FFD700',
        canopy: '#2D5016',
        understory: '#4A7C23',
        floor: '#8B6914',
        mycelium: '#6B3A7A',
        seedbank: '#8B4513',
      },
      fontFamily: {
        display: ['Cinzel', 'serif'],
        ui: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        terminal: ['VT323', 'monospace'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      spacing: {
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-6': '1.5rem',
        'space-8': '2rem',
        'space-12': '3rem',
        'space-16': '4rem',
        'space-20': '5rem',
        'space-24': '6rem',
      },
      maxWidth: {
        'content': '1400px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'amber-glow': '0 0 40px rgba(245,203,78,0.2)',
        'amber-card': '0 12px 40px rgba(245,203,78,0.1)',
        'amber-card-lg': '0 20px 60px rgba(245,203,78,0.12)',
        'builder-card': '0 20px 60px rgba(232,145,58,0.12)',
        'commander-card': '0 20px 60px rgba(155,109,209,0.12)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "cursor-blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.02)" },
        },
        "particle-drift": {
          "0%": { transform: "translate(0, 0)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translate(var(--drift-x, 30px), var(--drift-y, -50px))", opacity: "0" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-5px)" },
          "50%": { transform: "translateX(5px)" },
          "75%": { transform: "translateX(-5px)" },
        },
        "scroll-indicator": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(5px)" },
        },
        "coherence-pulse": {
          "0%, 100%": { transform: "scaleX(1)" },
          "50%": { transform: "scaleX(1.02)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "cursor-blink": "cursor-blink 1s step-end infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "particle-drift": "particle-drift var(--drift-duration, 15s) ease-in-out infinite",
        "shake": "shake 0.3s ease-in-out",
        "scroll-indicator": "scroll-indicator 2s ease-in-out infinite",
        "coherence-pulse": "coherence-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
